version: "3.0"

services:
  beacon-validator:
    restart: always
    build:
      context: ./image
      args:
          release_version: ${VERSION}
    image: nimbus
    env_file: .env
    volumes:
      - ./scripts:/usr/src/nimbus-eth2/nimbus-scripts:ro
      - ./validator_keys:/var/lib/nimbus/validator_keys
      - ./.nimbus:/var/lib/nimbus
    ports:
      - 9100:9100/tcp
      - 9100:9100/udp
    command: /usr/src/nimbus-eth2/nimbus-scripts/start-beacon-node-and-validator.sh
  geth:
      image: ethereum/client-go
      entrypoint: /bin/sh
      volumes:
          - ./geth-data:/root/.ethereum
          - ./scripts:/root/scripts
      ports:
          - 30303:30303/tcp
          - 30303:30303/udp
      env_file: .env
      command: /root/scripts/start-geth.sh
      restart: on-failure
