version: "3.0"

services:
  nimbus:
    image: statusim/nimbus-eth2:amd64-${NIMBUS_VERSION}
    container_name: nimbus
    restart: always
    stop_grace_period: 1m
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      # Metrics port
      - "127.0.0.1:8008:8008/tcp"
      # REST API port
      - "127.0.0.1:5052:5052/tcp"
    volumes:
      - ./nimbus-config:/home/user/nimbus-eth2/config:ro
      - ./validator_keys:/var/lib/nimbus/validator_keys:ro
      - ${CONSENSUS_DATA}:/var/lib/nimbus
      - ./secrets/jwtsecret:/secrets/jwtsecret:ro
    command: >-
      --network=${NETWORK}
      --config-file=/home/user/nimbus-eth2/config/config.toml
      ${NIMBUS_MEVBOOST_FLAGS}
    env_file: .env
  besu:
    image: hyperledger/besu:${BESU_VERSION}
    container_name: besu
    restart: always
    stop_grace_period: 3m
    command: >-
      --network ${NETWORK} 
      --config-file=/opt/besu/config/config.toml
    environment:
      - JAVA_OPTS=${JAVA_OPTS:--Xmx4g}
    volumes:
      - ./besu-config:/opt/besu/config:ro
      - ${EXECUTION_DATA}:/var/lib/besu
      - ./secrets:/opt/besu/secrets:ro
    ports:
        # RPC port
        # - "127.0.0.1:8545:8545/tcp"
        - "30303:30303/tcp"
        - "30303:30303/udp"
  mevboost:
    image: flashbots/mev-boost:${MEVBOOST_VERSION}
    container_name: mevboost
    restart: always
    command: >-
      -${NETWORK}
      -addr 0.0.0.0:18550
      -relay-check
      -relays ${MEV_RELAYS}
    env_file: .env
  eth2-client-metrics-exporter:
    image: gobitfly/eth2-client-metrics-exporter:${EXPORTER_VERSION}
    restart: unless-stopped
    container_name: metrics_exporter
    command:
      - --server.address=https://beaconcha.in/api/v1/client/metrics?apikey=${BEACHONCHAIN_API_KEY}
      - --system.partition=/host/rootfs
      - --beaconnode.type=nimbus
      - --beaconnode.address=http://nimbus:8008/metrics
    volumes:
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /:/host/rootfs:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    env_file: .env
      