version: "3.0"

services:
  nimbus:
    image: statusim/nimbus-eth2:amd64-${NIMBUS_VERSION}
    container_name: nimbus
    restart: always
    stop_grace_period: 1m
    entrypoint: /bin/bash
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      # Metrics port
      - "127.0.0.1:8008:8008/tcp"
    volumes:
      - ./scripts:/usr/src/nimbus-eth2/nimbus-scripts:ro
      - ./validator_keys:/var/lib/nimbus/validator_keys:ro
      - ${NIMBUS_DATA}:/var/lib/nimbus
      - ./secrets/jwtsecret:/secrets/jwtsecret:ro
    command: /usr/src/nimbus-eth2/nimbus-scripts/start-nimbus.sh
    env_file: .env
  nethermind:
    image: nethermind/nethermind:${NETHERMIND_VERSION}
    container_name: nethermind
    restart: always
    stop_grace_period: 3m
    volumes:
      -  ${NETHERMIND_DATA}:/nethermind/data
      - ./scripts:/nethermind/scripts:ro
      - ./secrets/jwtsecret:/secrets/jwtsecret:ro
    ports:
        - "127.0.0.1:8545:8545/tcp"
        - "30303:30303/tcp"
        - "30303:30303/udp"
    command: --datadir data
    environment:
        - NETHERMIND_CONFIG=${NETWORK}
        - NETHERMIND_INITCONFIG_WEBSOCKETSENABLED=false
        - NETHERMIND_JSONRPCCONFIG_ENABLED=true
        - NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES=[Admin,Web3,Eth,Subscribe,Net]
        - NETHERMIND_JSONRPCCONFIG_HOST=0.0.0.0
        - NETHERMIND_JSONRPCCONFIG_PORT=8545
        - NETHERMIND_JSONRPCCONFIG_JWTSECRETFILE=/secrets/jwtsecret
        - NETHERMIND_PRUNINGCONFIG_MODE=${PRUNING_MODE}
        - NETHERMIND_PRUNINGCONFIG_FULLPRUNINGMAXDEGREEOFPARALLELISM=${FULL_PRUNING_MAX_DEGREE_OF_PARALLELISM}
        - NETHERMIND_PRUNINGCONFIG_FULLPRUNINGTRIGGER=${FULL_PRUNING_TRIGGER}
        - NETHERMIND_PRUNINGCONFIG_CACHEMB=${PRUNING_CACHEMB}
        - NETHERMIND_SYNCCONFIG_SNAPSYNC=true
        - NETHERMIND_SYNCCONFIG_ANCIENTBODIESBARRIER=11052984
        - NETHERMIND_SYNCCONFIG_ANCIENTRECEIPTSBARRIER=11052984
        # - NETHERMIND_JSONRPCCONFIG_ADDITIONALRPCURLS=["http://0.0.0.0:8551|http;ws|net;eth;subscribe;engine;web3;client"]
        # - NETHERMIND_NETWORKCONFIG_EXTERNALIP=${STATIC_PUBLIC_IP}
        - NETHERMIND_HEALTHCHECKSCONFIG_ENABLED=true      
    env_file: .env
