version: "3.0"

services:
  nimbus:
    image: statusim/nimbus-eth2:amd64-${NIMBUS_VERSION}
    container_name: nimbus
    restart: always
    stop_grace_period: 1m
    entrypoint: /bin/bash
    ports:
      - 9001:9000/tcp
      - 9001:9000/udp
      # Metrics port
      # - 127.0.0.1:9190:9190/tcp
      # - 127.0.0.1:8008:8008/tcp
    volumes:
      - ./scripts:/usr/src/nimbus-eth2/nimbus-scripts:ro
      - ./validator_keys:/var/lib/nimbus/validator_keys:ro
      - ${NIMBUS_DATA}:/var/lib/nimbus
      - ./secrets/jwtsecret.txt:/secrets/jwtsecret:ro
    command: /usr/src/nimbus-eth2/nimbus-scripts/start-beacon-node-and-validator.sh
    env_file: .env
  nethermind:
    image: nethermind/nethermind:${NETHERMIND_VERSION}
    container_name: nethermind
    restart: always
    stop_grace_period: 3m
    volumes:
      -  ${NETHERMIND_DATA}:/nethermind/data
      - ./scripts:/nethermind/scripts:ro
      - ./secrets/jwtsecret.txt:/secrets/jwtsecret:ro
    entrypoint: /bin/bash
    ports:
        - 8545:8545/tcp
        - 8545:8545/udp
        - 8546:8546/tcp
        - 8546:8546/udp
        - 8551:8551/tcp
        - 8551:8551/udp
        - 30303:30303/tcp
        - 30303:30303/udp
    command: ./scripts/start-nethermind.sh
    env_file: .env
