data-path="/var/lib/besu"
sync-mode="X_CHECKPOINT"
data-storage-format="BONSAI"
engine-jwt-secret="/opt/besu/secrets/jwtsecret"
engine-host-allowlist=["*"]
engine-rpc-port=8551
host-allowlist=["*"]
rpc-http-cors-origins=["*"]
rpc-http-enabled=true
rpc-http-api=["ETH","NET","WEB3"]
rpc-http-host="0.0.0.0"
rpc-http-port="8545"
