# https://nimbus.guide/options.html

# Please uncomment the following line and set a suggested fee_recipient_address when running a validator.
# suggested-fee-recipient = "0x000..."

## nimbus-docker default configuration
network = "mainnet"
doppelganger-detection = false
web3-url = ["http://nethermind:8545"]
data-dir = "/var/lib/nimbus"
jwt-secret = "/secrets/jwtsecret"
status-bar = false
non-interactive = true
subscribe-all-subnets = true
enr-auto-update = true
tcp-port = 9000
udp-port = 9000

## Extra options
# nat = "extip:<INSERT_PUBLIC_IP_ADDRESS_HERE>"
# rpc = true
# rpc-address = 0.0.0.0
# rpc-port = 9190
# graffitti = ""
# metrics = true
# metrics-address = 0.0.0.0
# metrics-port = 8000